title: Hello, I'm Mary! Welcome to my blog!
author: MaryIv76
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It is an example of GitHub Pages that was done during a special course.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
